//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;

    
    public partial class Institute
    {
        
        public int Id { get; set; }
        [Required]
        [StringLength(255, ErrorMessage = "Must be of length 8 or more than 8", MinimumLength = 8)]
        [DataType(DataType.Password)]
        public string password { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        public string Course { get; set; }
        [Required]
        public string Scholarship { get; set; }
        [Required]
        public string Category { get; set; }
    }
}
